### ISSUE TITLE
Selective fields?

### ISSUE THREAD

**Issue by ottomata** [whale2/iow-hadoop-streaming#2]
Hi,

This is great! Thanks!

Question:  Is it possible to choose which of the Parquet fields should be given to the output format?  It'd be really nice if we could pick (a projection?) so that Hadoop Streaming could still take advantage of the columnar benefits Parquet provides.

-Andrew Otto

**Comment by whale2** [comment]
Hi Andrew,

I'm afraid I don't quite get it. Could you please provide an example?
Thanks.

Nikita

**Comment by ottomata** [comment]
Oh, sure.

So, the benefit of using Parquet, or any columnar data store, is the ability to only read fields that are needed for use at runtime, rather than all fields of a schema.  For example, Wikimedia has some data stored by Hive as Parquet on disk, but I'd like to be able to use this same data in a Hadoop Streaming job.  As far as I can tell, with this library will read every field of each record and present the whole record  to the Hadoop Streaming job as a JSON object.

Instead, it would be nice if one could tell this library that only a few specific fields are needed, and then return a JSON object either with only those fields, or all of the other non specified fields set to Null, or some other default.

E.g., parquet-mr does this for Avro inputs like this:

https://github.com/Parquet/parquet-mr/blob/master/parquet-avro/src/main/java/parquet/avro/AvroParquetInputFormat.java#L50

Then, at https://github.com/Parquet/parquet-mr/blob/master/parquet-avro/src/main/java/parquet/avro/AvroReadSupport.java#L62, it converts this 'projection' schema into a ```parquet.schema.MessageType``` that I think somehow informs Parquet to only return data for the projected fields.

**Comment by whale2** [comment]
I was confused by *output* format in your initial message. Of course,
making use of schema projection along with input format makes lot of sense.
I'll see what could be done here.

**Comment by ottomata** [comment]
Awesome, thanks for looking into it!

**Comment by ottomata** [comment]
Awesome!  This works!  Thanks so much for looking into this.
